+ Change optimization flags to treat each translation unit   individually instead of trying to do whole-code optimizations.  This   fixes a compilation problem on Turing that looks like:
  undefined reference to `typeinfo for rtt_imc::CDI_Mat_State_Builder<rtt_mc::OS_Mesh, rtt_imc::Multigroup_Frequency>'