Revert "Change one line of code to eliminate a warning..."
When building Draco with the combination of Intel 14 and gcc 4.8.2
(rather than the TOSS-default gcc 4.4.7), the change introduced by
r7621 triggers the following error in rng/test/ut_uniform.cpp:

/usr/projects/jayenne/devs/gaber/src/draco/src/rng/uniform.hpp(201): error: shift count is negative

  R123_CONSTEXPR Ftype factor = Ftype(1.)/(Ftype(1.) + ((maxTvalue<Utype>()>>ex_nowarn)));
                                                                             ^
  detected during instantiation of "Ftype r123::u01fixedpt<Ftype,Itype>(Itype) [with Ftype=double, Itype=r123array4x32::value_type={uint32_t={unsigned int}}]" at line 171 of "/usr/projects/jayenne/devs/gaber/src/draco/src/rng/test/ut_uniform.cpp"

I think that the authors of uniform.hpp probably hit this same
(nonsensical) error, which is why u01fixedpt (before r7621) contained
apparently redundant checks for non-negative values.  For now, revert
the change to preserve the ability to use uniform.hpp with newer
Intel/GCC combinations.